#theme: jekyll-theme-minimal
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Eric Schares
logo: /assets/pic.jpg
description: Iowa State University
google_analytics: G-GQLD70NE13
include: [".well-known"]
